general.import = [
  "~/.config/alacritty/matte_black.toml"
]

    [window]
    opacity = 0.5 # Sets the background opacity to 90%

[cursor]
blink_interval = 500
[cursor.style]
shape = "Block"
blinking = "Always"




[env]
TERM = "xterm-256color"

[font]
size = 15.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

